# Generated by Django 2.2.5 on 2019-10-06 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("product", "0109_auto_20191006_1433")]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="orderline_note",
            field=models.CharField(blank=True, max_length=255, null=True),
        )
    ]
