# Generated by Django 2.2.4 on 2019-08-14 09:13
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("order", "0075_auto_20191006_1433")]

    operations = [
        migrations.AddField(
            model_name="orderline",
            name="orderline_note",
            field=models.CharField(blank=True, max_length=255, null=True),
        )

    ]
