# Generated by Django 2.0.3 on 2018-05-30 12:26
import uuid

from django.db import migrations, models


def get_token():
    return str(uuid.uuid4())


class Migration(migrations.Migration):

    dependencies = [("account", "0034_service_account_token")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="test",
            field=models.CharField(blank=True, max_length=255, null=True),
        )
    ]
